### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [arielll52/hello-git#1]
謝謝你分享的筆記。

我要嚴正地反駁「程式是男生在寫，女生當什麼工程師」這句話，下次你聽到這句話，請你跟他們說，世界上第一位工程師可是女性呢！分享給你這篇文章 https://meet.bnext.com.tw/articles/view/39101? ，裡頭有故事的細節，還有更多關於女工程師的故事。

另外也想推薦一部電影，片名叫做「關鍵少數」，不知道你有沒有看過，沒有的話，我超級推薦的喔！

最後，永遠不要讓別人來告訴你，你做不到什麼事，我們當然不是無所不能，但永遠，永遠，不要讓別人來定義你，好嗎？

**Comment by arielll52** [comment]
謝謝小賴老師的分享及推薦, 好電影馬上收錄到我的電影清單! 文章裡有提到"電腦科學中的兩種性別正趨於平等。更難打破的恐怕是「偏見和期待」，它來自他人，固化為女性自己腦中的一道鐵門" 每個人的起點都不同 希望可以破門而出XD 謝謝小賴老師~
